version: '3'

services:
  nextjs:
    build:
      context: .  # Use the current directory for the Next.js app
      dockerfile: Dockerfile  # Dockerfile for Next.js should be in the same directory as docker-compose.yml
    ports:
      - "3000:3000"  # Expose Next.js app on localhost:3000
    env_file:
      - .env.local
    volumes:
      - ./nextjs:/app  # Mount the app code for hot reloading
    depends_on:
      - django

  django:
    build:
      context: ./backend  # Path to your Django app
      dockerfile: Dockerfile  # Dockerfile for Django should be in the backend directory
    ports:
      - "8000:8000"  # Expose Django app on localhost:8000
    env_file:
      - .env.local

    volumes:
      - ./backend:/app  # Mount the app code for hot reloading
